import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/attack_event.dart';

/// Генерация PDF-отчёта для врача
class PdfReportService {
  /// Создать PDF отчёт за период
  Future<Uint8List> generateReport({
    required List<AttackEvent> attacks,
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd.MM.yyyy');
    final dateTimeFormat = DateFormat('dd.MM.yyyy HH:mm');

    // Статистика
    final avgSeverity = attacks.isEmpty
        ? 0.0
        : attacks.map((a) => a.severity).reduce((a, b) => a + b) /
            attacks.length;

    // Подсчёт триггеров
    final triggerCount = <String, int>{};
    for (final attack in attacks) {
      for (final trigger in attack.triggers) {
        triggerCount[trigger] = (triggerCount[trigger] ?? 0) + 1;
      }
    }
    final sortedTriggers = triggerCount.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Заголовок
          pw.Header(
            level: 0,
            child: pw.Text(
              'VasoLog - Raynaud\'s Phenomenon Report',
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Period: ${dateFormat.format(startDate)} - ${dateFormat.format(endDate)}',
            style: const pw.TextStyle(fontSize: 14),
          ),
          pw.Text(
            'Generated: ${dateTimeFormat.format(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 20),

          // Сводка
          pw.Header(level: 1, text: 'Summary'),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            cellAlignment: pw.Alignment.centerLeft,
            data: [
              ['Metric', 'Value'],
              ['Total Attacks', '${attacks.length}'],
              ['Average Severity (RCS)', avgSeverity.toStringAsFixed(1)],
              [
                'Most Common Trigger',
                sortedTriggers.isNotEmpty ? sortedTriggers.first.key : 'N/A'
              ],
              [
                'Avg. Temperature During Attacks',
                _avgTemp(attacks),
              ],
            ],
          ),
          pw.SizedBox(height: 20),

          // Таблица триггеров
          if (sortedTriggers.isNotEmpty) ...[
            pw.Header(level: 1, text: 'Trigger Analysis'),
            pw.TableHelper.fromTextArray(
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              data: [
                ['Trigger', 'Count', '% of Attacks'],
                ...sortedTriggers.map((e) => [
                      e.key,
                      '${e.value}',
                      '${(e.value / attacks.length * 100).toStringAsFixed(0)}%',
                    ]),
              ],
            ),
            pw.SizedBox(height: 20),
          ],

          // Детальный лог приступов
          pw.Header(level: 1, text: 'Attack Log'),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: 9,
            ),
            cellStyle: const pw.TextStyle(fontSize: 8),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(1),
              2: const pw.FlexColumnWidth(1.5),
              3: const pw.FlexColumnWidth(1),
              4: const pw.FlexColumnWidth(2),
            },
            data: [
              ['Date/Time', 'RCS', 'Color Phase', 'Temp °C', 'Triggers'],
              ...attacks.map((a) => [
                    dateTimeFormat.format(a.timestamp),
                    '${a.severity}/10',
                    a.colorPhase,
                    a.temperature?.toStringAsFixed(1) ?? '-',
                    a.triggers.join(', '),
                  ]),
            ],
          ),

          pw.SizedBox(height: 30),
          pw.Divider(),
          pw.SizedBox(height: 10),
          pw.Text(
            'This report was generated by VasoLog app and is intended '
            'for informational purposes. Please consult your healthcare '
            'provider for medical advice.',
            style: const pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  String _avgTemp(List<AttackEvent> attacks) {
    final temps =
        attacks.where((a) => a.temperature != null).map((a) => a.temperature!);
    if (temps.isEmpty) return 'N/A';
    final avg = temps.reduce((a, b) => a + b) / temps.length;
    return '${avg.toStringAsFixed(1)}°C';
  }
}
